// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"entgo.io/bug/ent/migrate"
	"entgo.io/bug/ulid"

	"entgo.io/bug/ent/hoge"
	"entgo.io/bug/ent/hogeadministrator"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Hoge is the client for interacting with the Hoge builders.
	Hoge *HogeClient
	// HogeAdministrator is the client for interacting with the HogeAdministrator builders.
	HogeAdministrator *HogeAdministratorClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Hoge = NewHogeClient(c.config)
	c.HogeAdministrator = NewHogeAdministratorClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Hoge:              NewHogeClient(cfg),
		HogeAdministrator: NewHogeAdministratorClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Hoge:              NewHogeClient(cfg),
		HogeAdministrator: NewHogeAdministratorClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Hoge.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Hoge.Use(hooks...)
	c.HogeAdministrator.Use(hooks...)
}

// HogeClient is a client for the Hoge schema.
type HogeClient struct {
	config
}

// NewHogeClient returns a client for the Hoge from the given config.
func NewHogeClient(c config) *HogeClient {
	return &HogeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `hoge.Hooks(f(g(h())))`.
func (c *HogeClient) Use(hooks ...Hook) {
	c.hooks.Hoge = append(c.hooks.Hoge, hooks...)
}

// Create returns a builder for creating a Hoge entity.
func (c *HogeClient) Create() *HogeCreate {
	mutation := newHogeMutation(c.config, OpCreate)
	return &HogeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Hoge entities.
func (c *HogeClient) CreateBulk(builders ...*HogeCreate) *HogeCreateBulk {
	return &HogeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Hoge.
func (c *HogeClient) Update() *HogeUpdate {
	mutation := newHogeMutation(c.config, OpUpdate)
	return &HogeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HogeClient) UpdateOne(h *Hoge) *HogeUpdateOne {
	mutation := newHogeMutation(c.config, OpUpdateOne, withHoge(h))
	return &HogeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HogeClient) UpdateOneID(id ulid.ID) *HogeUpdateOne {
	mutation := newHogeMutation(c.config, OpUpdateOne, withHogeID(id))
	return &HogeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Hoge.
func (c *HogeClient) Delete() *HogeDelete {
	mutation := newHogeMutation(c.config, OpDelete)
	return &HogeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HogeClient) DeleteOne(h *Hoge) *HogeDeleteOne {
	return c.DeleteOneID(h.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *HogeClient) DeleteOneID(id ulid.ID) *HogeDeleteOne {
	builder := c.Delete().Where(hoge.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HogeDeleteOne{builder}
}

// Query returns a query builder for Hoge.
func (c *HogeClient) Query() *HogeQuery {
	return &HogeQuery{
		config: c.config,
	}
}

// Get returns a Hoge entity by its id.
func (c *HogeClient) Get(ctx context.Context, id ulid.ID) (*Hoge, error) {
	return c.Query().Where(hoge.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HogeClient) GetX(ctx context.Context, id ulid.ID) *Hoge {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryHogeAdministrators queries the hoge_administrators edge of a Hoge.
func (c *HogeClient) QueryHogeAdministrators(h *Hoge) *HogeAdministratorQuery {
	query := &HogeAdministratorQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := h.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(hoge.Table, hoge.FieldID, id),
			sqlgraph.To(hogeadministrator.Table, hogeadministrator.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, hoge.HogeAdministratorsTable, hoge.HogeAdministratorsColumn),
		)
		fromV = sqlgraph.Neighbors(h.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *HogeClient) Hooks() []Hook {
	return c.hooks.Hoge
}

// HogeAdministratorClient is a client for the HogeAdministrator schema.
type HogeAdministratorClient struct {
	config
}

// NewHogeAdministratorClient returns a client for the HogeAdministrator from the given config.
func NewHogeAdministratorClient(c config) *HogeAdministratorClient {
	return &HogeAdministratorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `hogeadministrator.Hooks(f(g(h())))`.
func (c *HogeAdministratorClient) Use(hooks ...Hook) {
	c.hooks.HogeAdministrator = append(c.hooks.HogeAdministrator, hooks...)
}

// Create returns a builder for creating a HogeAdministrator entity.
func (c *HogeAdministratorClient) Create() *HogeAdministratorCreate {
	mutation := newHogeAdministratorMutation(c.config, OpCreate)
	return &HogeAdministratorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of HogeAdministrator entities.
func (c *HogeAdministratorClient) CreateBulk(builders ...*HogeAdministratorCreate) *HogeAdministratorCreateBulk {
	return &HogeAdministratorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for HogeAdministrator.
func (c *HogeAdministratorClient) Update() *HogeAdministratorUpdate {
	mutation := newHogeAdministratorMutation(c.config, OpUpdate)
	return &HogeAdministratorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HogeAdministratorClient) UpdateOne(ha *HogeAdministrator) *HogeAdministratorUpdateOne {
	mutation := newHogeAdministratorMutation(c.config, OpUpdateOne, withHogeAdministrator(ha))
	return &HogeAdministratorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HogeAdministratorClient) UpdateOneID(id ulid.ID) *HogeAdministratorUpdateOne {
	mutation := newHogeAdministratorMutation(c.config, OpUpdateOne, withHogeAdministratorID(id))
	return &HogeAdministratorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for HogeAdministrator.
func (c *HogeAdministratorClient) Delete() *HogeAdministratorDelete {
	mutation := newHogeAdministratorMutation(c.config, OpDelete)
	return &HogeAdministratorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HogeAdministratorClient) DeleteOne(ha *HogeAdministrator) *HogeAdministratorDeleteOne {
	return c.DeleteOneID(ha.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *HogeAdministratorClient) DeleteOneID(id ulid.ID) *HogeAdministratorDeleteOne {
	builder := c.Delete().Where(hogeadministrator.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HogeAdministratorDeleteOne{builder}
}

// Query returns a query builder for HogeAdministrator.
func (c *HogeAdministratorClient) Query() *HogeAdministratorQuery {
	return &HogeAdministratorQuery{
		config: c.config,
	}
}

// Get returns a HogeAdministrator entity by its id.
func (c *HogeAdministratorClient) Get(ctx context.Context, id ulid.ID) (*HogeAdministrator, error) {
	return c.Query().Where(hogeadministrator.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HogeAdministratorClient) GetX(ctx context.Context, id ulid.ID) *HogeAdministrator {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryHoge queries the hoge edge of a HogeAdministrator.
func (c *HogeAdministratorClient) QueryHoge(ha *HogeAdministrator) *HogeQuery {
	query := &HogeQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := ha.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(hogeadministrator.Table, hogeadministrator.FieldID, id),
			sqlgraph.To(hoge.Table, hoge.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, hogeadministrator.HogeTable, hogeadministrator.HogeColumn),
		)
		fromV = sqlgraph.Neighbors(ha.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *HogeAdministratorClient) Hooks() []Hook {
	return c.hooks.HogeAdministrator
}
