// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/bug/ent/hoge"
	"entgo.io/bug/ulid"
	"entgo.io/ent/dialect/sql"
)

// Hoge is the model entity for the Hoge schema.
type Hoge struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HogeQuery when eager-loading is set.
	Edges HogeEdges `json:"edges"`
}

// HogeEdges holds the relations/edges for other nodes in the graph.
type HogeEdges struct {
	// HogeAdministrators holds the value of the hoge_administrators edge.
	HogeAdministrators []*HogeAdministrator `json:"hoge_administrators,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HogeAdministratorsOrErr returns the HogeAdministrators value or an error if the edge
// was not loaded in eager-loading.
func (e HogeEdges) HogeAdministratorsOrErr() ([]*HogeAdministrator, error) {
	if e.loadedTypes[0] {
		return e.HogeAdministrators, nil
	}
	return nil, &NotLoadedError{edge: "hoge_administrators"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hoge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hoge.FieldID, hoge.FieldName:
			values[i] = new(sql.NullString)
		case hoge.FieldCreatedAt, hoge.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Hoge", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hoge fields.
func (h *Hoge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hoge.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				h.ID = ulid.ID(value.String)
			}
		case hoge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				h.CreatedAt = value.Time
			}
		case hoge.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				h.UpdatedAt = value.Time
			}
		case hoge.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				h.Name = value.String
			}
		}
	}
	return nil
}

// QueryHogeAdministrators queries the "hoge_administrators" edge of the Hoge entity.
func (h *Hoge) QueryHogeAdministrators() *HogeAdministratorQuery {
	return (&HogeClient{config: h.config}).QueryHogeAdministrators(h)
}

// Update returns a builder for updating this Hoge.
// Note that you need to call Hoge.Unwrap() before calling this method if this Hoge
// was returned from a transaction, and the transaction was committed or rolled back.
func (h *Hoge) Update() *HogeUpdateOne {
	return (&HogeClient{config: h.config}).UpdateOne(h)
}

// Unwrap unwraps the Hoge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (h *Hoge) Unwrap() *Hoge {
	_tx, ok := h.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hoge is not a transactional entity")
	}
	h.config.driver = _tx.drv
	return h
}

// String implements the fmt.Stringer.
func (h *Hoge) String() string {
	var builder strings.Builder
	builder.WriteString("Hoge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", h.ID))
	builder.WriteString("created_at=")
	builder.WriteString(h.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(h.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(h.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Hoges is a parsable slice of Hoge.
type Hoges []*Hoge

func (h Hoges) config(cfg config) {
	for _i := range h {
		h[_i].config = cfg
	}
}
