// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/bug/ent/hoge"
	"entgo.io/bug/ent/hogeadministrator"
	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ulid"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HogeAdministratorQuery is the builder for querying HogeAdministrator entities.
type HogeAdministratorQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.HogeAdministrator
	withHoge   *HogeQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HogeAdministratorQuery builder.
func (haq *HogeAdministratorQuery) Where(ps ...predicate.HogeAdministrator) *HogeAdministratorQuery {
	haq.predicates = append(haq.predicates, ps...)
	return haq
}

// Limit adds a limit step to the query.
func (haq *HogeAdministratorQuery) Limit(limit int) *HogeAdministratorQuery {
	haq.limit = &limit
	return haq
}

// Offset adds an offset step to the query.
func (haq *HogeAdministratorQuery) Offset(offset int) *HogeAdministratorQuery {
	haq.offset = &offset
	return haq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (haq *HogeAdministratorQuery) Unique(unique bool) *HogeAdministratorQuery {
	haq.unique = &unique
	return haq
}

// Order adds an order step to the query.
func (haq *HogeAdministratorQuery) Order(o ...OrderFunc) *HogeAdministratorQuery {
	haq.order = append(haq.order, o...)
	return haq
}

// QueryHoge chains the current query on the "hoge" edge.
func (haq *HogeAdministratorQuery) QueryHoge() *HogeQuery {
	query := &HogeQuery{config: haq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := haq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := haq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hogeadministrator.Table, hogeadministrator.FieldID, selector),
			sqlgraph.To(hoge.Table, hoge.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, hogeadministrator.HogeTable, hogeadministrator.HogeColumn),
		)
		fromU = sqlgraph.SetNeighbors(haq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HogeAdministrator entity from the query.
// Returns a *NotFoundError when no HogeAdministrator was found.
func (haq *HogeAdministratorQuery) First(ctx context.Context) (*HogeAdministrator, error) {
	nodes, err := haq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hogeadministrator.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (haq *HogeAdministratorQuery) FirstX(ctx context.Context) *HogeAdministrator {
	node, err := haq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HogeAdministrator ID from the query.
// Returns a *NotFoundError when no HogeAdministrator ID was found.
func (haq *HogeAdministratorQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = haq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hogeadministrator.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (haq *HogeAdministratorQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := haq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HogeAdministrator entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HogeAdministrator entity is found.
// Returns a *NotFoundError when no HogeAdministrator entities are found.
func (haq *HogeAdministratorQuery) Only(ctx context.Context) (*HogeAdministrator, error) {
	nodes, err := haq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hogeadministrator.Label}
	default:
		return nil, &NotSingularError{hogeadministrator.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (haq *HogeAdministratorQuery) OnlyX(ctx context.Context) *HogeAdministrator {
	node, err := haq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HogeAdministrator ID in the query.
// Returns a *NotSingularError when more than one HogeAdministrator ID is found.
// Returns a *NotFoundError when no entities are found.
func (haq *HogeAdministratorQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = haq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hogeadministrator.Label}
	default:
		err = &NotSingularError{hogeadministrator.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (haq *HogeAdministratorQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := haq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HogeAdministrators.
func (haq *HogeAdministratorQuery) All(ctx context.Context) ([]*HogeAdministrator, error) {
	if err := haq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return haq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (haq *HogeAdministratorQuery) AllX(ctx context.Context) []*HogeAdministrator {
	nodes, err := haq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HogeAdministrator IDs.
func (haq *HogeAdministratorQuery) IDs(ctx context.Context) ([]ulid.ID, error) {
	var ids []ulid.ID
	if err := haq.Select(hogeadministrator.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (haq *HogeAdministratorQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := haq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (haq *HogeAdministratorQuery) Count(ctx context.Context) (int, error) {
	if err := haq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return haq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (haq *HogeAdministratorQuery) CountX(ctx context.Context) int {
	count, err := haq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (haq *HogeAdministratorQuery) Exist(ctx context.Context) (bool, error) {
	if err := haq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return haq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (haq *HogeAdministratorQuery) ExistX(ctx context.Context) bool {
	exist, err := haq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HogeAdministratorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (haq *HogeAdministratorQuery) Clone() *HogeAdministratorQuery {
	if haq == nil {
		return nil
	}
	return &HogeAdministratorQuery{
		config:     haq.config,
		limit:      haq.limit,
		offset:     haq.offset,
		order:      append([]OrderFunc{}, haq.order...),
		predicates: append([]predicate.HogeAdministrator{}, haq.predicates...),
		withHoge:   haq.withHoge.Clone(),
		// clone intermediate query.
		sql:    haq.sql.Clone(),
		path:   haq.path,
		unique: haq.unique,
	}
}

// WithHoge tells the query-builder to eager-load the nodes that are connected to
// the "hoge" edge. The optional arguments are used to configure the query builder of the edge.
func (haq *HogeAdministratorQuery) WithHoge(opts ...func(*HogeQuery)) *HogeAdministratorQuery {
	query := &HogeQuery{config: haq.config}
	for _, opt := range opts {
		opt(query)
	}
	haq.withHoge = query
	return haq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HogeAdministrator.Query().
//		GroupBy(hogeadministrator.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (haq *HogeAdministratorQuery) GroupBy(field string, fields ...string) *HogeAdministratorGroupBy {
	grbuild := &HogeAdministratorGroupBy{config: haq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := haq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return haq.sqlQuery(ctx), nil
	}
	grbuild.label = hogeadministrator.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.HogeAdministrator.Query().
//		Select(hogeadministrator.FieldCreatedAt).
//		Scan(ctx, &v)
func (haq *HogeAdministratorQuery) Select(fields ...string) *HogeAdministratorSelect {
	haq.fields = append(haq.fields, fields...)
	selbuild := &HogeAdministratorSelect{HogeAdministratorQuery: haq}
	selbuild.label = hogeadministrator.Label
	selbuild.flds, selbuild.scan = &haq.fields, selbuild.Scan
	return selbuild
}

func (haq *HogeAdministratorQuery) prepareQuery(ctx context.Context) error {
	for _, f := range haq.fields {
		if !hogeadministrator.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if haq.path != nil {
		prev, err := haq.path(ctx)
		if err != nil {
			return err
		}
		haq.sql = prev
	}
	return nil
}

func (haq *HogeAdministratorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HogeAdministrator, error) {
	var (
		nodes       = []*HogeAdministrator{}
		withFKs     = haq.withFKs
		_spec       = haq.querySpec()
		loadedTypes = [1]bool{
			haq.withHoge != nil,
		}
	)
	if haq.withHoge != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, hogeadministrator.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HogeAdministrator).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HogeAdministrator{config: haq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, haq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := haq.withHoge; query != nil {
		if err := haq.loadHoge(ctx, query, nodes, nil,
			func(n *HogeAdministrator, e *Hoge) { n.Edges.Hoge = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (haq *HogeAdministratorQuery) loadHoge(ctx context.Context, query *HogeQuery, nodes []*HogeAdministrator, init func(*HogeAdministrator), assign func(*HogeAdministrator, *Hoge)) error {
	ids := make([]ulid.ID, 0, len(nodes))
	nodeids := make(map[ulid.ID][]*HogeAdministrator)
	for i := range nodes {
		if nodes[i].hoge_id == nil {
			continue
		}
		fk := *nodes[i].hoge_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(hoge.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "hoge_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (haq *HogeAdministratorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := haq.querySpec()
	_spec.Node.Columns = haq.fields
	if len(haq.fields) > 0 {
		_spec.Unique = haq.unique != nil && *haq.unique
	}
	return sqlgraph.CountNodes(ctx, haq.driver, _spec)
}

func (haq *HogeAdministratorQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := haq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (haq *HogeAdministratorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   hogeadministrator.Table,
			Columns: hogeadministrator.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: hogeadministrator.FieldID,
			},
		},
		From:   haq.sql,
		Unique: true,
	}
	if unique := haq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := haq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hogeadministrator.FieldID)
		for i := range fields {
			if fields[i] != hogeadministrator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := haq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := haq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := haq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := haq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (haq *HogeAdministratorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(haq.driver.Dialect())
	t1 := builder.Table(hogeadministrator.Table)
	columns := haq.fields
	if len(columns) == 0 {
		columns = hogeadministrator.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if haq.sql != nil {
		selector = haq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if haq.unique != nil && *haq.unique {
		selector.Distinct()
	}
	for _, p := range haq.predicates {
		p(selector)
	}
	for _, p := range haq.order {
		p(selector)
	}
	if offset := haq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := haq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HogeAdministratorGroupBy is the group-by builder for HogeAdministrator entities.
type HogeAdministratorGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hagb *HogeAdministratorGroupBy) Aggregate(fns ...AggregateFunc) *HogeAdministratorGroupBy {
	hagb.fns = append(hagb.fns, fns...)
	return hagb
}

// Scan applies the group-by query and scans the result into the given value.
func (hagb *HogeAdministratorGroupBy) Scan(ctx context.Context, v any) error {
	query, err := hagb.path(ctx)
	if err != nil {
		return err
	}
	hagb.sql = query
	return hagb.sqlScan(ctx, v)
}

func (hagb *HogeAdministratorGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range hagb.fields {
		if !hogeadministrator.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := hagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (hagb *HogeAdministratorGroupBy) sqlQuery() *sql.Selector {
	selector := hagb.sql.Select()
	aggregation := make([]string, 0, len(hagb.fns))
	for _, fn := range hagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(hagb.fields)+len(hagb.fns))
		for _, f := range hagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(hagb.fields...)...)
}

// HogeAdministratorSelect is the builder for selecting fields of HogeAdministrator entities.
type HogeAdministratorSelect struct {
	*HogeAdministratorQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (has *HogeAdministratorSelect) Scan(ctx context.Context, v any) error {
	if err := has.prepareQuery(ctx); err != nil {
		return err
	}
	has.sql = has.HogeAdministratorQuery.sqlQuery(ctx)
	return has.sqlScan(ctx, v)
}

func (has *HogeAdministratorSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := has.sql.Query()
	if err := has.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
