// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Hoge is the predicate function for hoge builders.
type Hoge func(*sql.Selector)

// HogeAdministrator is the predicate function for hogeadministrator builders.
type HogeAdministrator func(*sql.Selector)
